prog:main.o menu.o background.o perso.o objet.o enigf.o minimap.o score.o
	 gcc main.o menu.o background.o perso.o objet.o enigf.o minimap.o score.o -o prog -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -g
main.o:main.c
	gcc -c main.c -g
menu.o:menu.c
	gcc -c menu.c -g
background.o:background.c
	gcc -c background.c -g
perso.o:perso.c
	gcc -c perso.c -g
objet.o:objet.c
	gcc -c objet.c -g
enigf.o:enigf.c
	gcc -c enigf.c -g
minimap.o:minimap.c
	gcc -c minimap.c -g
score.o:score.c
	gcc -c score.c -g



